### ISSUE TITLE
Snag list

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/kdb-studio-2#31]
Just a bunch of small issues that need fixing ...

Functional snags ...

 - if you delete the port number, it renders `NaN`
 - the table columns appear clickable
 - in the table panel, I'm not sure tables should be selectable - you just click them to perform a one-off action
 - when there are no tables, the panel is blank - needs a 'no tables' style placeholder
 - the pane numbering needs to be more logical
 - there needs to be some distinction between the various panes / panels. Perhaps a thin grey line, or light gray background?
 - when you switch server panes, it triggers an animation. I'd be happy to just disable the 'appear' animations if that is simpler?
 - clicking on a table shows the data, but also hides the columns (if expanded) - perhaps add a button next to the table name for executing the query? I'd expect a click to just open the column details
 - when there are many tabs open, the tab heading list needs to be scrollable
 - we need a way to close a tab
 - on the edit server modal, the save button should only be enabled if an edit is made
 - if I run an empty query, the results table just spins
 - switching between raw and table causes the app to show a vertical scrollbar (in fact, it is quite easy to end up with both vertical and horizontal scrollbars)
 - delete all `*-old` files

Others ..

 - move to a consistent styling => Prettier

**Comment by OiNutter** [comment]
Closing this for now, have moved outstanding items to a seperate issue so they can be closed with commits and discussed individually.
