### ISSUE TITLE
the pane numbering needs to be more logical

### ISSUE THREAD

**Issue by OiNutter** [ScottLogic/kdb-studio-2#40]
I'm assuming this means the numbering of the Server/Connection pivotitems along the top. I would question whether we even need that numbering?

@ColinEberhardt what are your thoughts with this?

**Comment by OiNutter** [comment]
@ColinEberhardt is this still relevant now we're putting filenames into the tabs?

**Comment by ColinEberhardt** [comment]
nope - time to close.
