### ISSUE TITLE
raw button is broken

### ISSUE THREAD

**Issue by adavies42** [ScottLogic/kdb-studio-2#61]
when i click on "Raw", nothing happens

**Comment by ColinEberhardt** [comment]
thanks for raising - we'll look into this.

**Comment by OiNutter** [comment]
Fixed in 34e617dda6f4a8c54f3df912aa9b37464ef28949. Pending new release. Currently blocked by attempts to test on multiple os's in the pipeline.

**Comment by OiNutter** [comment]
New release available with this fixed. https://github.com/ScottLogic/kdb-studio-2/releases/tag/v1.0.1
